# -*- mode: ruby -*-
# vi: set ft=ruby :

# -*- mode: ruby -*-
#vi: set ft=ruby :

require 'yaml'
require 'fileutils'

$CONFIG_ERRORS = File.join(File.dirname(__FILE__), "setup/scripts/errors.rb")

if File.exist?($CONFIG_ERRORS)
    require $CONFIG_ERRORS
end

$CONFIG_HANDLER = File.join(File.dirname(__FILE__), "setup/scripts/config_handler.rb")

if File.exist?($CONFIG_HANDLER)
    require $CONFIG_HANDLER
end

case ARGV[0]
when "provision"
    system "./setup/pre-provision.sh"
    system "./setup/provision.sh"
end

case ARGV[0]
when "up"
    case ARGV[1]
    when "--provision"
        system "./setup/pre-provision.sh"
        system "./setup/provision.sh"
    else
        system "./setup/pre-provision.sh"
    end
end

vagrant_folder_path = Dir.pwd

if !CONFIG['vagrant_name']
    vagrant_name = vagrant_folder_path.split('/').last.sub(/^(\w)/) {|s| s.capitalize}
else
    vagrant_name = CONFIG['vagrant_name']
end

if !CONFIG['folder_path']
    folder_path = vagrant_folder_path
else
    folder_path = CONFIG['folder_path']
end

if !CONFIG['folder_name']
    folder_name = vagrant_folder_path.split('/').last
else
    folder_name = CONFIG['folder_name']
end

if !CONFIG['php_version']
    php_version = "7.2"
else
    php_version = CONFIG['php_version']
end

if !CONFIG['phantomjs']
    phantomjs = 'yes'
else
    phantomjs = CONFIG['phantomjs']
end

if !CONFIG['use_chromedriver']
    use_chromedriver = 'yes'
else
    use_chromedriver = CONFIG['use_chromedriver']
end

Vagrant.configure("2") do |config|

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true

  config.vm.network :forwarded_port, guest: 80, host: CONFIG['vagrant_port'], auto_correct: true
  config.vm.network :forwarded_port, guest: 6379, host: 6379, auto_correct: true
  config.vm.network "private_network", ip: CONFIG['vagrant_ip']

  config.vm.synced_folder "./", vagrant_folder_path, nfs: true, create: true

  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: ".ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: ".ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.ssh/known_hosts", destination: ".ssh/known_hosts"

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.name = CONFIG['vagrant_name']
  end

  config.vm.provision :shell,
    #if there a line that only consists of 'mesg n' in /root/.profile, replace it with 'tty -s && mesg n'
    :inline => "(grep -q -E '^mesg n$' /root/.profile && sed -i 's/^mesg n$/tty -s \\&\\& mesg n/g' /root/.profile && echo 'Ignore the previous error about stdin not being a tty. Fixing it now...') || exit 0;"

  config.vm.provision "shell" do |s|
    s.path = "setup/provision.sh"
    s.args = [
        folder_name,
        CONFIG['vagrant_ip'],
        CONFIG['db_user'],
        CONFIG['db_password'],
        vagrant_name,
        folder_path,
        php_version,
        phantomjs,
        use_chromedriver
    ]
  end
end
